In [2]:
import numpy as np
import pandas as pd
import time

**Задание 1**

In [3]:
!wget https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
!unzip /content/Data.zip

df = pd.DataFrame()
for i in range(0, 10):
    students_info = pd.read_csv(f'/content/Data/Students_info_{i}.csv')
    students_marks = pd.read_csv(f'/content/Data/Students_marks_{i}.csv')

    merged_data = pd.merge(students_info, students_marks, on='index') # объединяем информацию для каждого блока студентов с оценками для этого блока студентов по индексу, так как они должны совпадать
    df = pd.concat([df, merged_data], ignore_index=True) # объединяем блоки с информацией + оценками студентов между собой
df

--2024-02-09 17:14:23--  https://github.com/hse-ds/iad-intro-ds/raw/master/2023/homeworks/Data.zip
Resolving github.com (github.com)... 20.27.177.113
Connecting to github.com (github.com)|20.27.177.113|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip [following]
--2024-02-09 17:14:23--  https://raw.githubusercontent.com/hse-ds/iad-intro-ds/master/2023/homeworks/Data.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16727 (16K) [application/zip]
Saving to: ‘Data.zip’

Data.zip            100%[===================>]  16.33K  --.-KB/s    in 0.003s

2024-02-09 17:14:24 (4.95 MB/s) - ‘Data.zip’ saved [16727/16727]

Archive:  /content/Data.zip
   creating: Data/
  inflating: Data/Students_info_0.csv
  inflating: Data/Students_info_1.csv
  inflating: Data/Students_info_2.csv
  inflating: Data/Students_info_3.csv
  inflating: Data/Students_info_4.csv
  inflating: Data/Students_info_5.csv
  inflating: Data/Students_info_6.csv
  inflating: Data/Students_info_7.csv
  inflating: Data/Students_info_8.csv
  inflating: Data/Students_info_9.csv
  inflating: Data/Students_marks_0.csv
  inflating: Data/Students_marks_1.csv
  inflating: Data/Students_marks_2.csv
  inflating: Data/Students_marks_3.csv
  inflating: Data/Students_marks_4.csv
  inflating: Data/Students_marks_5.csv
  inflating: Data/Students_marks_6.csv
  inflating: Data/Students_marks_7.csv
  inflating: Data/Students_marks_8.csv
  inflating: Data/Students_marks_9.csv

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

**Задание 2**

In [4]:
df.drop('index', axis=1 , inplace=True)
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95
996,male,group C,high school,free/reduced,none,group10,62,55,55
997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,female,group D,some college,standard,completed,group10,68,78,77
999,female,group D,some college,free/reduced,none,group10,77,86,86

**Задание 3**

In [5]:
df.shape

(1000, 9)

**Задание 4**

In [6]:
df[['math score','reading score','writing score']].agg([min, max, np.mean, np.std])

      math score  reading score  writing score
min      0.00000      17.000000      10.000000
max    100.00000     100.000000     100.000000
mean    66.08900      69.169000      68.054000
std     15.16308      14.600192      15.195657

**Задание 5**

In [7]:
print(df.isnull().any())
if df.isnull().any().sum() == 0:
  print('Нет пропущенных значений')

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course        False
group                          False
math score                     False
reading score                  False
writing score                  False
dtype: bool
Нет пропущенных значений

**Задание 6**

In [8]:
df.mean(numeric_only=True)

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7**

In [9]:
print('Математика:')
print(df.groupby('test preparation course')['math score'].mean())
print('\nЧтение:')
print(df.groupby('test preparation course')['reading score'].mean())
print('\nПисьмо:')
print(df.groupby('test preparation course')['writing score'].mean())

print('\nВывод: У тех, кто проходил курс, средняя оценка на 11% выше (в среднем по каждому из предметов) чем у тех, кто не проходил курс')

Математика:
test preparation course
completed    69.695531
none         64.077882
Name: math score, dtype: float64

Чтение:
test preparation course
completed    73.893855
none         66.534268
Name: reading score, dtype: float64

Письмо:
test preparation course
completed    74.418994
none         64.504673
Name: writing score, dtype: float64

Вывод: У тех, кто проходил курс, средняя оценка на 11% выше (в среднем по каждому из предметов) чем у тех, кто не проходил курс

**Задание 8**

In [10]:
print(*df['lunch'].unique())

standard free/reduced

**Задание 9**

In [11]:
df.rename(columns={'parental level of education': 'education', 'test preparation course': 'test preparation'}, inplace = True)
df

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95
996,male,group C,high school,free/reduced,none,group10,62,55,55
997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,female,group D,some college,standard,completed,group10,68,78,77
999,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [12]:
passmark = 50

**Задание 10**

In [13]:
print('Доля студентов, сдавших экзамен по математике:')
print(len(df[df['math score'] >= passmark])/len(df))
print('\nДоля студентов, проходивших курс подготовки к экзамену и сдавших экзамен по математике:')
print(len(df[(df['math score'] >= passmark) & (df['test preparation'] == 'completed')])/len(df[df['test preparation'] == 'completed']))
print('\nДоля женщин, не проходивших курс подготовки к экзамену и не сдавших экзамен по математике:')
print(len(df[(df['math score'] < passmark) & (df['test preparation'] == 'none') & (df['gender'] == 'female')])/len(df[(df['test preparation'] == 'none') & (df['gender'] == 'female')]))

Доля студентов, сдавших экзамен по математике:
0.865

Доля студентов, проходивших курс подготовки к экзамену и сдавших экзамен по математике:
0.9217877094972067

Доля женщин, не проходивших курс подготовки к экзамену и не сдавших экзамен по математике:
0.20958083832335328

**Задание 11**

In [14]:
print('Средний балл за экзамен по чтению для каждой этнической группы:')
start = time.time()
print(df.groupby('race/ethnicity')['reading score'].mean())
end = time.time() - start
print('\nВремя выполнения:', end)

print('\nМинимальный балл за экзамен по письму для каждого уровня образования:')
start = time.time()
print(df.groupby('education')['writing score'].min())
end = time.time() - start
print('\nВремя выполнения:', end)

Средний балл за экзамен по чтению для каждой этнической группы:
race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

Время выполнения: 0.0067310333251953125

Минимальный балл за экзамен по письму для каждого уровня образования:
education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

Время выполнения: 0.004868268966674805

**Задание 12**

In [15]:
print('Средний балл за экзамен по чтению для каждой этнической группы:')
start = time.time()
dict = {}
names = df['race/ethnicity'].unique() # получаем список различных групп
for group in sorted(names):
  subset = df[df['race/ethnicity'] == group] # выделяем группу отдельно от других
  average = subset['reading score'].mean() # находим среднее значение для выделенной группы
  dict[group] = '{:.6f}'.format(average) # округляем до 6 знаков после запятой + добавляем в словарь
for name in dict.keys():
  print(name, '  ', dict[name])
end = time.time() - start
print('\nВремя выполнения:', end)

print('\nМинимальный балл за экзамен по письму для каждого уровня образования:')

start = time.time()
dict = {}
names = df['education'].unique()  # получаем список различных типов образования
for type in sorted(names):
  subset = df[df['education'] == type] # выделяем тип отдельно от других
  average = subset['writing score'].min() # находим минимальное значение для выделенной группы
  dict[type] = average # добавляем в словарь
for name in dict.keys():
  print(name, '  ', dict[name])
end = time.time() - start
print('\nВремя выполнения:', end)

Средний балл за экзамен по чтению для каждой этнической группы:
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571

Время выполнения: 0.007035255432128906

Минимальный балл за экзамен по письму для каждого уровня образования:
associate's degree    35
bachelor's degree    38
high school    15
master's degree    46
some college    19
some high school    10

Время выполнения: 0.013237237930297852

**Задание 13**

In [16]:
pd.pivot_table(df,index=['gender','education'], aggfunc={'math score':np.mean, 'reading score':np.mean, 'writing score':np.mean})

                           math score  reading score  writing score
gender education
female associate's degree   65.250000      74.120690      74.000000
       bachelor's degree    68.349206      77.285714      78.380952
       high school          59.351064      68.202128      66.691489
       master's degree      66.500000      76.805556      77.638889
       some college         65.406780      73.550847      74.050847
       some high school     59.296703      69.109890      68.285714
male   associate's degree   70.764151      67.433962      65.405660
       bachelor's degree    70.581818      68.090909      67.654545
       high school          64.705882      61.480392      58.539216
       master's degree      74.826087      73.130435      72.608696
       some college         69.009259      64.990741      63.148148
       some high school     67.840909      64.693182      61.375000

**Задание 14**

In [17]:
df['Math_PassStatus'] = np.where(df['math score'] < passmark, 'F', 'P')
print('Сдали экзамен по математике:', len(df[df['Math_PassStatus'] == 'P']))
print('Не сдали экзамен по математике:', len(df[df['Math_PassStatus'] == 'F']))

df['Read_PassStatus'] = np.where(df['reading score'] < passmark, 'F', 'P')
print('\nСдали экзамен по чтению:', len(df[df['Read_PassStatus'] == 'P']))
print('Не сдали экзамен по чтению:', len(df[df['Read_PassStatus'] == 'F']))

df['Writ_PassStatus'] = np.where(df['writing score'] < passmark, 'F', 'P')
print('\nСдали экзамен по письму:', len(df[df['Writ_PassStatus'] == 'P']))
print('Не сдали экзамен по письму:', len(df[df['Writ_PassStatus'] == 'F']))

Сдали экзамен по математике: 865
Не сдали экзамен по математике: 135

Сдали экзамен по чтению: 910
Не сдали экзамен по чтению: 90

Сдали экзамен по письму: 886
Не сдали экзамен по письму: 114

**Задание 15**

In [18]:
df['OverAll_PassStatus'] = np.where(((df['math score'] < passmark) | (df['reading score'] < passmark) | (df['writing score'] < passmark)), 'F', 'P')
print('Сдали все экзамены:', len(df[df['OverAll_PassStatus'] == 'P']))
df

Сдали все экзамены: 812

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,Math_PassStatus,Read_PassStatus,Writ_PassStatus,OverAll_PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,P,P,P,P
1,female,group C,some college,standard,completed,group1,69,90,88,P,P,P,P
2,female,group B,master's degree,standard,none,group1,90,95,93,P,P,P,P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,F,P,F,F
4,male,group C,some college,standard,none,group1,76,78,75,P,P,P,P
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,P,P,P,P
996,male,group C,high school,free/reduced,none,group10,62,55,55,P,P,P,P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,P,P,P,P
998,female,group D,some college,standard,completed,group10,68,78,77,P,P,P,P
999,female,group D,some college,free/reduced,none,group10,77,86,86,P,P,P,P

**Задание 16**

In [19]:
def GetGrade(average_mark):
  if average_mark < 50:
    return 'F'
  if average_mark >= 50 and average_mark < 60:
    return 'E'
  if average_mark >= 60 and average_mark < 70:
    return 'D'
  if average_mark >= 70 and average_mark < 80:
    return 'C'
  if average_mark >= 80 and average_mark <= 90:
    return 'B'
  if average_mark > 90:
    return 'A'
df['Grade'] = (df['math score'] + df['reading score'] + df['writing score'])/3
df['Grade'] = df['Grade'].apply(GetGrade)
print(df['Grade'].value_counts().sort_index())

A     50
B    148
C    261
D    256
E    182
F    103
Name: Grade, dtype: int64